# /etc/apache2/sites-available/badhat.dev.conf

Define SITE badhat.dev
Define CONF /etc/apache2/badhat

###############################################
# PRODUCTION
# http://badhat.dev
# http://www.badhat.dev
###############################################

<VirtualHost *:80>
    Define MODE prod
    Define ROOT /var/www/${SITE}

    ServerName ${SITE}
    ServerAlias www.${SITE}

    DocumentRoot ${ROOT}/public

    ErrorLog ${APACHE_LOG_DIR}/${SITE}-${MODE}-error.log
    CustomLog ${APACHE_LOG_DIR}/${SITE}-${MODE}-access.log combined

    php_admin_value open_basedir "${ROOT}/app/:${ROOT}/add/:${ROOT}/public/:/tmp/"

    Include ${CONF}/badhat-common.conf

    <Directory "${ROOT}/public">
        Include ${CONF}/badhat-directory.conf
    </Directory>

    UnDefine ROOT
    UnDefine MODE
</VirtualHost>


###############################################
# LOCAL
# http://local.badhat.dev
###############################################


<VirtualHost *:80>
    Define MODE local
    Define ROOT /var/www/${SITE}.${MODE}

    ServerName ${MODE}.${SITE}
    DocumentRoot ${ROOT}/public

    ErrorLog ${APACHE_LOG_DIR}/${SITE}-${MODE}-error.log
    CustomLog ${APACHE_LOG_DIR}/${SITE}-${MODE}-access.log combined

    php_admin_value open_basedir "${ROOT}/app/:${ROOT}/add/:${ROOT}/public/:/tmp/"

    Include ${CONF}/badhat-common.conf
    Include ${CONF}/badhat-local.conf

    <Directory "${ROOT}/public">
        Include ${CONF}/badhat-directory.conf
    </Directory>

    UnDefine ROOT
    UnDefine MODE
</VirtualHost>


###############################################
# STAGE
# http://stage.badhat.dev
###############################################

<VirtualHost *:80>
    Define MODE stage
    Define ROOT /var/www/${SITE}.${MODE}

    ServerName ${MODE}.${SITE}
    DocumentRoot ${ROOT}/public

    ErrorLog ${APACHE_LOG_DIR}/${SITE}-${MODE}-error.log
    CustomLog ${APACHE_LOG_DIR}/${SITE}-${MODE}-access.log combined

    php_admin_value open_basedir "${ROOT}/app/:${ROOT}/add/:${ROOT}/public/:/tmp/"

    Include ${CONF}/badhat-common.conf
    Include ${CONF}/badhat-stage.conf

    <Directory "${ROOT}/public">
        Include ${CONF}/badhat-directory.conf
    </Directory>

    UnDefine ROOT
    UnDefine MODE
</VirtualHost>

UnDefine SITE
UnDefine CONF
